#!/bin/bash

# install spotify
curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
sudo apt-get update && sudo apt-get install spotify-client

# add perms
sudo chmod a+wr /usr/share/spotify
sudo chmod a+wr /usr/share/spotify/Apps -R
# download spicetify
curl -fsSL https://raw.githubusercontent.com/spicetify/cli/main/install.sh | sh
spicetify

echo "install marketplace if you didn't do that yet; afterwards install comfy,
then import the config in ./spicetify_theme_config"